### PR TITLE
Fix keymap & fix doc typo

### PR DESCRIPTION
**Pull request by voldikss**
I have set this keymap in my vimrc
```vim
inoremap jj <Esc>
inoremap jk <Esc>
```
but this line of code seems not to remove that keymap. 
https://github.com/kizza/actionmenu.nvim/blob/b74782cf59c009a37067f5e22c8e9f8cc8a255d6/ftplugin/actionmenu.vim#L50

So `<nowait>` might be necessary.

### CODE REVIEW

**Comment by kizza** [comment]
Howdy @voldikss.  Thanks for your pr!  I had a browse through the docs (`:help mapclear`), and yes, appears `mapclear` doesn't clear `i` mode mappings.  

I like the cleanness of just clearing all mappings so am leaning towards just adding `imapclear <buffer>` below the existing `mapclear <buffer>`. Thoughts?

**Comment by voldikss** [comment]
imapclear is better

**Comment by kizza** [comment]
Kewl.  If you rebase your PR to drop the "Make moving keymap `nowait`" commit for an `imapclear` I'd love to merge it.

**Comment by voldikss** [comment]
Sure. I will rebase it soon

**Comment by voldikss** [comment]
I have done that.

**Comment by kizza** [comment]
Awesome - thanks so much for your input @voldikss

**Pull request merged**
